apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: qeb-hwt
  namespace: default
spec:
  taskRef:
    name: qeb-hwt-task
  inputs:
    resources:
      - name: git-repo # target path is /workspace otherwise targetPath: specific needs to be included
        resourceSpec:
          type: git
          params:
            - name: url
              value: $(inputs.params.GITHUB_HEAD_REPO_URL)
            - name: revision
              value: $(inputs.params.REVISION)
    params:
      - name: WORKFLOW_ID
        description: "a UUID for the workflow instance"
      - name: GITHUB_EVENT_TYPE
        description: "GitHub event Type"
        value: "thoth_thamos_advise"
      - name: GITHUB_CHECK_RUN_ID
        description: "ID of the check-run that shall carry the thamos advise."
      - name: GITHUB_INSTALLATION_ID
        description: "GitHub App Installation ID"
      - name: ORIGIN
        description: "Origin of the repo where the Pull Request was opened.."
      - name: GITHUB_BASE_REPO_URL
        description: "URL of the GitHub repository containing the Pull Request."
      - name: GITHUB_HEAD_REPO_URL
        description: URL of the Pull Request's head commit.
      - name: REVISION
        description: Pull Request head SHA.
      - name: THOTH_HOST
        description: Host used to talk to User-API for Thoth.
  
  podTemplate:
    volumes:
      - name: custom-volume
        emptyDir: {}